config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_footer.html.haml
- unless user_signed_in?
  %footer.bg-light.footer.mt-auto.py-3
    .container.d-flex.justify-content-between.mx-auto.text-muted
      %span
        © #{Date.today.year} 
        = link_to "NarraLabs", "https://www.narralabs.com", target: "_blank", class: "text-decoration-none text-reset"
      %ul.d-inline.float-end.list-inline.mb-0
        %li.list-inline-item.mr-3= footer_link_to "Terms", terms_path
        %li.list-inline-item.mr-3= footer_link_to "Privacy", privacy_path

app/views/shared/_head.html.haml
%title= Rails.configuration.application_name
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
%link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css", :integrity => "sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==", :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload"
= javascript_include_tag "application", "data-turbo-track": "reload", defer: true
= favicon_link_tag 'logo/logo-cm.webp', type: 'image/webp'

app/views/shared/_navbar.html.haml
- if current_user != true_user
  .alert.alert-warning.text-center
    You're logged in as
    %b
      = current_user.name
      (#{current_user.email})
    = link_to stop_impersonating_madmin_impersonates_path, method: :post do
      = icon("fas", "times")
      Logout

- if !user_signed_in?
  %nav.navbar.navbar-expand-sm.navbar-light.bg-light.border-bottom.border-2.border-dark.py-3
    .container.mx-auto
      = image_tag "logo/logo-cm.webp", alt: "Checkmule Logo", size: "30x30", class: "cm-logo"
      = link_to Rails.configuration.application_name, root_path, class: "navbar-brand fs-5"
      %button.navbar-toggler{"aria-controls" => "navbarsExample04", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarMain", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarMain.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mt-2.mt-md-0
        %ul.navbar-nav
          %li.nav-item.px-2.text-muted= link_to "What's New", announcements_path, class: "text-secondary nav-link #{unread_announcements(current_user)}"        
          .vertical-divider.mx-4
          %li.nav-item.mx-4= link_to "Sign Up", new_user_registration_path, class: "nav-link text-dark "
          %li.nav-item.btn-shadow= link_to "Login", new_user_session_path, class: "nav-link px-3"

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  .container.mt-4.mx-auto
    %div{:class => "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show", :role => "alert"}
      = message
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}